services:
  frontend:
    build:
      context: ./frontend
      target: dev
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports: ["5173:5173"]
    environment:
      VITE_API_URL: http://api:3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - api

  api:
    build:
      context: ./backend
      target: dev
    command: npm run start:dev
    ports: ["3000:3000"]
    environment:
      CORS_ORIGIN: "http://localhost:5173"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app?schema=public"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 3s
      retries: 5
  
volumes:
  frontend_node_modules:
  backend_node_modules:
  pgdata: